apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: justelyes44.azurecr.io/angular:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4600
      imagePullSecrets:
        - name: acr-credential      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular
  name: angular-app
spec:
  ports:
    - name: http
      port: 4600
      protocol: TCP
      targetPort: 4600
  type: LoadBalancer
  selector:
    app: angular